### ISSUE TITLE
Make a release?

### ISSUE THREAD

**Issue by samueltardieu** [makkarpov/telegrambot4s-fix#1]
Your version seems to be the only one maintained and up-to-date with the latest Telegram bot API (such as the `Int`→`Long` change). Maybe you should change the package name and make an interim release, while you try to obtain control of the `bot4s` organization.

Thanks for your work.

**Comment by makkarpov** [comment]
Actualy it is already released here: https://maven.m-k.mx/com/bot4s/

Don't you think that I copy JARs to my projects by hand? :)

If Mukel will not respond to my request I will probably make complete fork that I'm trying to avoid now.

**Comment by samueltardieu** [comment]
I thought you were using a `mill _.jvm.publishLocal` then get it from your Ivy cache, but this is perfect, I'll use this as a resolver, thanks!
